version: '3'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin123_habittracker
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin123_habittracker@db:5432/habittracker

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000

